pipeline {
    agent any

    environment {
        DOCKER_COMPOSE_FILE = 'docker-compose.yml'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Images') {
            steps {
                sh 'docker compose -f $DOCKER_COMPOSE_FILE build'
            }
        }

        stage('Start Containers') {
            steps {
                sh 'docker compose -f $DOCKER_COMPOSE_FILE up -d'
            }
        }

        stage('Test App') {
            steps {
                sh 'curl -f http://localhost || echo "App not responding yet"'
            }
        }
    }

    post {
        always {
            sh 'docker compose -f $DOCKER_COMPOSE_FILE ps'
        }
    }
}
